export const dummytender = [
  {
    tenderId: "GT2024001",
    department: "Ministry of Infrastructure Development",
    description: "Construction of a new highway connecting major cities.",
    closingDate: "2024-08-15",
    budget: "₹10,000,000",
    contactPerson: {
      name: "John Doe",
      email: "johndoe@example.com",
      phone: "+1234567890",
    },
  },
  {
    tenderId: "GT2024002",
    department: "Ministry of Health",
    description: "Supply and installation of medical equipment for hospitals.",
    closingDate: "2024-09-10",
    budget: "₹5,000,000",
    contactPerson: {
      name: "Jane Smith",
      email: "janesmith@example.com",
      phone: "+1987654321",
    },
  },
  {
    tenderId: "GT2024003",
    department: "Ministry of Education",
    description: "Renovation of schools across the country.",
    closingDate: "2024-08-30",
    budget: "₹8,000,000",
    contactPerson: {
      name: "Michael Brown",
      email: "mbrown@example.com",
      phone: "+1654321897",
    },
  },
  {
    tenderId: "GT2024004",
    department: "Ministry of Agriculture",
    description:
      "Implementation of irrigation systems for rural farming communities.",
    closingDate: "2024-09-15",
    budget: "₹7,500,000",
    contactPerson: {
      name: "Emily Wilson",
      email: "ewilson@example.com",
      phone: "+1789456123",
    },
  },
  {
    tenderId: "GT2024005",
    department: "Ministry of Transport",
    description: "Upgrade of public transport infrastructure in urban areas.",
    closingDate: "2024-09-05",
    budget: "₹6,500,000",
    contactPerson: {
      name: "David Lee",
      email: "davidlee@example.com",
      phone: "+1346798521",
    },
  },
  {
    tenderId: "GT2024006",
    department: "Ministry of Environment",
    description: "Development of national parks and protected areas.",
    closingDate: "2024-08-25",
    budget: "₹9,000,000",
    contactPerson: {
      name: "Olivia Green",
      email: "ogreen@example.com",
      phone: "+1876543210",
    },
  },
  {
    tenderId: "GT2024007",
    department: "Ministry of Finance",
    description: "Consultancy services for tax reform initiatives.",
    closingDate: "2024-09-20",
    budget: "₹4,000,000",
    contactPerson: {
      name: "William Taylor",
      email: "wtaylor@example.com",
      phone: "+1567890123",
    },
  },
  {
    tenderId: "GT2024008",
    department: "Ministry of Social Welfare",
    description: "Expansion of social security programs.",
    closingDate: "2024-09-08",
    budget: "₹3,500,000",
    contactPerson: {
      name: "Sophia Martinez",
      email: "smartinez@example.com",
      phone: "+1122334455",
    },
  },
  {
    tenderId: "GT2024009",
    department: "Ministry of Energy",
    description: "Installation of renewable energy systems in rural areas.",
    closingDate: "2024-08-28",
    budget: "₹7,200,000",
    contactPerson: {
      name: "Ethan Clark",
      email: "eclark@example.com",
      phone: "+1447392018",
    },
  },
  {
    tenderId: "GT2024010",
    department: "Ministry of Culture",
    description: "Preservation and restoration of historical monuments.",
    closingDate: "2024-09-12",
    budget: "₹5,800,000",
    contactPerson: {
      name: "Isabella White",
      email: "iwhite@example.com",
      phone: "+1789564123",
    },
  },
  {
    tenderId: "GT2024011",
    department: "Ministry of Communications",
    description: "Upgrade of national telecommunications infrastructure.",
    closingDate: "2024-09-25",
    budget: "₹8,500,000",
    contactPerson: {
      name: "Mason Harris",
      email: "mharris@example.com",
      phone: "+1346798021",
    },
  },
  {
    tenderId: "GT2024012",
    department: "Ministry of Justice",
    description: "Construction of new courthouses in major cities.",
    closingDate: "2024-09-18",
    budget: "₹6,700,000",
    contactPerson: {
      name: "Ava Carter",
      email: "acarter@example.com",
      phone: "+1567894321",
    },
  },
  {
    tenderId: "GT2024013",
    department: "Ministry of Defense",
    description: "Procurement of military equipment and vehicles.",
    closingDate: "2024-09-02",
    budget: "₹12,000,000",
    contactPerson: {
      name: "Logan Martin",
      email: "lmartin@example.com",
      phone: "+1987654321",
    },
  },
  {
    tenderId: "GT2024014",
    department: "Ministry of Urban Development",
    description: "Urban planning and development projects.",
    closingDate: "2024-08-22",
    budget: "₹8,300,000",
    contactPerson: {
      name: "Chloe Wilson",
      email: "cwilson@example.com",
      phone: "+1223344556",
    },
  },
  {
    tenderId: "GT2024015",
    department: "Ministry of Tourism",
    description: "Promotion of tourism and hospitality infrastructure.",
    closingDate: "2024-09-14",
    budget: "₹4,600,000",
    contactPerson: {
      name: "Jackson Rodriguez",
      email: "jrodriguez@example.com",
      phone: "+1346798012",
    },
  },
  {
    tenderId: "GT2024016",
    department: "Ministry of Science and Technology",
    description: "Research and development grants for technology innovation.",
    closingDate: "2024-09-30",
    budget: "₹9,500,000",
    contactPerson: {
      name: "Madison Moore",
      email: "mmoore@example.com",
      phone: "+1789456123",
    },
  },
  {
    tenderId: "GT2024017",
    department: "Ministry of Water Resources",
    description: "Water conservation and management initiatives.",
    closingDate: "2024-08-31",
    budget: "₹6,000,000",
    contactPerson: {
      name: "Lucas Garcia",
      email: "lgarcia@example.com",
      phone: "+1567890234",
    },
  },
  {
    tenderId: "GT2024018",
    department: "Ministry of Human Resource Development",
    description: "Training programs for skill development and employment.",
    closingDate: "2024-09-06",
    budget: "₹5,200,000",
    contactPerson: {
      name: "Lily Adams",
      email: "ladams@example.com",
      phone: "+1346798567",
    },
  },
  {
    tenderId: "GT2024019",
    department: "Ministry of Commerce and Industry",
    description: "Promotion of exports and international trade.",
    closingDate: "2024-09-16",
    budget: "₹7,800,000",
    contactPerson: {
      name: "Sophie Turner",
      email: "sturner@example.com",
      phone: "+1122334455",
    },
  },
];
